print("Let do some multiplication")
input1 = input("Enter a value: ")
input2 = input("Enter another value: ")
answer = int(input1) * int(input2)
print("Multiplication of", input1, "and", input2, "is", answer)
